"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const medicine_category_controller_1 = __importDefault(require("../controller/medicine/medicine-category.controller"));
const medicine_controller_1 = __importDefault(require("../controller/medicine/medicine.controller"));
const medicine_usage_controller_1 = __importDefault(require("../controller/medicine/medicine-usage.controller"));
const router = express_1.default.Router();
router.get("/cate", medicine_category_controller_1.default.getAll);
router.get("/cate/:id", medicine_category_controller_1.default.getById);
router.post("/cate/", medicine_category_controller_1.default.create);
router.put("/cate/:id", medicine_category_controller_1.default.update);
router.delete("/cate/:id", medicine_category_controller_1.default.delete);
router.get("/usage", medicine_usage_controller_1.default.getAll);
router.get("/usage/:id", medicine_usage_controller_1.default.getById);
router.post("/usage/add", medicine_usage_controller_1.default.addMedUsage);
router.put("/usage/edit/:id", medicine_usage_controller_1.default.editMedUsage);
router.delete("/usage/remove/:id", medicine_usage_controller_1.default.deleteMedUsage);
router.get("/", medicine_controller_1.default.getMedicineUser);
router.post("/search", medicine_controller_1.default.searchMed);
// router.get("/filter", medicineController.filterMedicine);
router.get("/createdAdd", medicine_controller_1.default.getCreateAdd);
router.get("/admin", medicine_controller_1.default.getMedicineAdmin);
router.post("/", medicine_controller_1.default.create);
router.get("/:id", medicine_controller_1.default.getById);
router.put("/:id", medicine_controller_1.default.update);
router.delete("/:id", medicine_controller_1.default.delete);
exports.default = router;
