export const NameEnum = {
  GENERAL_INTERNAL: "Nội tổng quát",
  CARDIOLOGY: "Nội tim mạch",
  PULMONOLOGY: "Nội hô hấp",
  GASTROENTEROLOGY: "Nội tiêu hóa",
  NEUROLOGY: "Nội thần kinh",
  ENDOCRINOLOGY_DIABETES: "Nội tiết - Đái tháo đường",
  HEMATOLOGY: "Huyết học",
  NEPHROLOGY: "Thận - Tiết niệu",
  IMMUNOLOGY: "Dị ứng - Miễn dịch",
  RHEUMATOLOGY: "Cơ xương khớp",
  GENERAL_SURGERY: "Ngoại tổng quát",
  NEUROSURGERY: "Ngoại thần kinh",
  CARDIOTHORACIC_SURGERY: "Ngoại tim mạch",
  UROLOGY: "Ngoại tiết niệu",
  ORTHOPEDIC_SURGERY: "Ngoại chấn thương chỉnh hình",
  GI_SURGERY: "Ngoại tiêu hóa",
  THORACIC_SURGERY: "Phẫu thuật lồng ngực",
  VASCULAR_SURGERY: "Phẫu thuật mạch máu",
  PEDIATRIC_SURGERY: "Ngoại nhi",
  OBSTETRICS_GYNECOLOGY: "Sản phụ khoa",
  REPRODUCTIVE_MEDICINE: "Hiếm muộn / Hỗ trợ sinh sản",
  PEDIATRICS: "Nhi khoa",
  NEONATOLOGY: "Nhi sơ sinh",
  GERIATRICS: "Lão khoa",
  DERMATOLOGY: "Da liễu",
  ENT: "Tai Mũi Họng",
  OPHTHALMOLOGY: "Mắt",
  DENTOMAXILLOFACIAL: "Răng - Hàm - Mặt",
  ONCOLOGY: "Ung bướu",
  TRADITIONAL_MEDICINE: "Y học cổ truyền",
  REHABILITATION: "Phục hồi chức năng",
  NUCLEAR_MEDICINE: "Y học hạt nhân",
  ANESTHESIA_CRITICAL_CARE: "Gây mê - Hồi sức",
  TOXICOLOGY: "Chống độc",
  PSYCHIATRY: "Tâm thần",
  CLINICAL_PSYCHOLOGY: "Tâm lý lâm sàng",
  FORENSIC_MEDICINE: "Pháp y",
  ENDOSCOPY: "Nội soi",
  EMERGENCY_CARE: "Hồi sức cấp cứu",
  RADIOLOGY: "Chẩn đoán hình ảnh",
  LABORATORY_MEDICINE: "Xét nghiệm",
  PATHOLOGY: "Giải phẫu bệnh",
  MICROBIOLOGY: "Vi sinh",
  MOLECULAR_MEDICINE: "Sinh học phân tử y học",
  PUBLIC_HEALTH: "Y tế công cộng",
  EPIDEMIOLOGY: "Dịch tễ học",
  CLINICAL_NUTRITION: "Dinh dưỡng lâm sàng",
  PREVENTIVE_MEDICINE: "Y học dự phòng",
  HEALTH_ADMINISTRATION: "Quản lý y tế",
  BIOMEDICAL_ENGINEERING: "Công nghệ y sinh",
} as const;
export type DiseaseUsageGroupEnum = keyof typeof NameEnum;
// export const InternalEnum = {
//   GENERAL_INTERNAL: "Nội tổng quát",
//   CARDIOLOGY: "Nội tim mạch",
//   PULMONOLOGY: "Nội hô hấp",
//   GASTROENTEROLOGY: "Nội tiêu hóa",
//   NEUROLOGY: "Nội thần kinh",
//   ENDOCRINOLOGY_DIABETES: "Nội tiết - Đái tháo đường",
//   HEMATOLOGY: "Huyết học",
//   NEPHROLOGY: "Thận - Tiết niệu",
//   IMMUNOLOGY: "Dị ứng - Miễn dịch",
//   RHEUMATOLOGY: "Cơ xương khớp",
// } as const;
// export const SurgeryEnum = {
  // GENERAL_SURGERY: "Ngoại tổng quát",
  // NEUROSURGERY: "Ngoại thần kinh",
  // CARDIOTHORACIC_SURGERY: "Ngoại tim mạch",
  // UROLOGY: "Ngoại tiết niệu",
  // ORTHOPEDIC_SURGERY: "Ngoại chấn thương chỉnh hình",
  // GI_SURGERY: "Ngoại tiêu hóa",
  // THORACIC_SURGERY: "Phẫu thuật lồng ngực",
  // VASCULAR_SURGERY: "Phẫu thuật mạch máu",
  // PEDIATRIC_SURGERY: "Ngoại nhi",
// } as const;
// export const OpgEnum = {
//   OBSTETRICS_GYNECOLOGY: "Sản phụ khoa",
//   REPRODUCTIVE_MEDICINE: "Hiếm muộn / Hỗ trợ sinh sản",
//   PEDIATRICS: "Nhi khoa",
//   NEONATOLOGY: "Nhi sơ sinh",
//   GERIATRICS: "Lão khoa",
// } as const;
// export const OthersEnum = {
  // DERMATOLOGY: "Da liễu",
  // ENT: "Tai Mũi Họng",
  // OPHTHALMOLOGY: "Mắt",
  // DENTOMAXILLOFACIAL: "Răng - Hàm - Mặt",
  // ONCOLOGY: "Ung bướu",
  // TRADITIONAL_MEDICINE: "Y học cổ truyền",
  // REHABILITATION: "Phục hồi chức năng",
  // NUCLEAR_MEDICINE: "Y học hạt nhân",
  // ANESTHESIA_CRITICAL_CARE: "Gây mê - Hồi sức",
  // TOXICOLOGY: "Chống độc",
  // PSYCHIATRY: "Tâm thần",
  // CLINICAL_PSYCHOLOGY: "Tâm lý lâm sàng",
  // FORENSIC_MEDICINE: "Pháp y",
  // ENDOSCOPY: "Nội soi",
  // EMERGENCY_CARE: "Hồi sức cấp cứu",
// } as const;
// export const LabEnum = {
//   RADIOLOGY: "Chẩn đoán hình ảnh",
//   LABORATORY_MEDICINE: "Xét nghiệm",
//   PATHOLOGY: "Giải phẫu bệnh",
//   MICROBIOLOGY: "Vi sinh",
//   MOLECULAR_MEDICINE: "Sinh học phân tử y học",
//   PUBLIC_HEALTH: "Y tế công cộng",
//   EPIDEMIOLOGY: "Dịch tễ học",
//   CLINICAL_NUTRITION: "Dinh dưỡng lâm sàng",
// } as const;
// export const PreventiveEnum = {
//   PREVENTIVE_MEDICINE: "Y học dự phòng",
//   HEALTH_ADMINISTRATION: "Quản lý y tế",
//   BIOMEDICAL_ENGINEERING: "Công nghệ y sinh",
// } as const;
// export type InternalNameEnum = keyof typeof InternalEnum;
// export type SurgeryNameEnum = keyof typeof SurgeryEnum;
// export type OpgNameEnum = keyof typeof OpgEnum;
// export type OthersNameEnum = keyof typeof OthersEnum;
// export type LabNameEnum = keyof typeof LabEnum;
// export type PreventiveNameEnum = keyof typeof PreventiveEnum;
